intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{asio}: include/{hxx ixx txx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_base/include/" "-I$src_base/include/"

# Export options.
#
lib{asio}:
{
  cxx.export.poptions = "-I$out_base/include/" "-I$src_base/include/"
  cxx.export.libs = $intf_libs
}

# Install into include directory recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
